# Generated by Django 4.1.3 on 2022-12-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='website',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
