# Generated by Django 4.1.3 on 2022-12-30 03:18

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactmodel_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator(message='Введите корректный email!!!')]),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid', flags=re.RegexFlag['IGNORECASE'], inverse_match=False, message='Поставьте точку в конце!', regex='\\.$')]),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='website',
            field=models.URLField(max_length=250),
        ),
    ]
