# Generated by Django 4.1.3 on 2023-04-13 21:32

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contactmodel_email_alter_contactmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='our_mission',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid', flags=re.RegexFlag['IGNORECASE'], inverse_match=False, message='Поставьте точку в конце!', regex='')]),
        ),
    ]
