# Generated by Django 4.1.3 on 2023-04-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_about_our_mission_alter_contactmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Публиковать'),
        ),
    ]
