# Generated by Django 4.1.3 on 2023-04-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_about_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='is_published',
            field=models.BooleanField(),
        ),
    ]
