# Generated by Django 4.1.3 on 2023-04-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_about_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='is_published',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='mini_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='our_mission',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_subscription',
            field=models.CharField(max_length=500),
        ),
    ]
