# Generated by Django 4.1.3 on 2023-04-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_about_is_published_alter_about_mini_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsubscription',
            name='website',
            field=models.URLField(default='https://www.youtube.com/watch?v=DWHB6nTyKDI'),
        ),
    ]
