# Generated by Django 4.1.3 on 2023-04-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_aboutsubscription_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsubscription',
            name='website',
        ),
        migrations.AddField(
            model_name='about',
            name='website',
            field=models.URLField(default='https://www.youtube.com/watch?v=DWHB6nTyKDI'),
        ),
    ]
